site_name: Robot IA
repo_url: https://github.com/glaucomunsberg/robot-ia
repo_name: glaucomunsberg/robot-ia
site_dir: site
theme:
  name: material
  logo: images/logos/robot-ia-white.png
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
  favicon: images/logos/favicon.png
  palette:
    primary: blue
  features:
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tooltips
    - search.suggest
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - navigation.tabs.sticky
    - toc.follow
plugins:
  - mermaid2:
      arguments:
        securityLevel: 'loose'
        startOnLoad: true
  - search
  - blog:
      archive: false
  - offline
  - privacy
  - social:
      cards: true
  - tags:
      enabled: true
      tags_file: tags.md
  - group:
      plugins:
        - optimize
        - minify
extra:
  homepage: https://glaucomunsberg.github.io/robot-ia/
  social:
    - icon: fontawesome/brands/github
      link: https://glaucomunsberg.github.io/robot-ia/
    - icon: fontawesome/brands/github
      link: https://github.com/glaucomunsberg/robot-ia
  analytics:
    provider: google
    property: G-AAAAAAA
    feedback:
      title: Essa página foi útil?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Essa página foi útil
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: Essa página não foi útil
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/glaucomunsberg/robot-ia/issues/new?title=página a melhorar" target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Política de Cookies
    description: >-
      Utilizamos cookies para garantir a melhor experiência em nosso site. Ao continuar navegando, você concorda com nossa política de cookies.
  
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: diagram
          format: !!python/name:mermaid2.fence_mermaid
  - admonition
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - def_list
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - toc:
copyright: © 2024 Robot IA
extra_css:
  - extra/stylesheets/extra.css
extra_javascript:
  - path: extra/javascript/register-mermaid-icons.js
    type: module

# MENU NAVIGATION
nav:
  - Robot IA:
    - Robot IA: index.md
    - Process:
      - Components: components/index.md
      - Assembly: assembly/index.md
      - Wiring: wiring/index.md
      - Programming: programming/index.md
    - Project:
      - Features: project/features.md
      - Roadmap: project/roadmap.md
      - Versions: project/version.md
      - Architecture: project/architecture.md
      - Design: project/design.md
  - Components:
    - List: components/index.md
    - Buying: components/buying.md
  - 3D Models:
    - List: 3dmodels/index.md
  - Assembly:
    - Resume: assembly/index.md
    - Chassis: assembly/chassis.md
    - Body: assembly/body.md
  - Wiring:
    - Resume: wiring/index.md
  - Setup:
    - Resume: setup/index.md
    - Transfer Files: setup/sync.md
  - Programming:
    - Resume: programming/index.md
    - Brain:
      - Introduction: programming/brain/index.md
      - Structure: programming/brain/structure.md
      - Cortex: programming/brain/cortex.md
      - Behavior: programming/brain/behavior.md
    - Protocols:
      - Introduction: programming/protocols/index.md
      - Ideas:
        - Idea: programming/protocols/ideia.md
        - Command: programming/protocols/command.md
        - Rule: programming/protocols/rule.md
      - Data:
        - Sensors: programming/protocols/sensor.md
  - Blog: blog/index.md